name: Publish
on:
  [ release ]
jobs:
  publish:
    name: Publish Github
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          check-latest: true
      - name: Publish Github
        run: |
          chmod +x ./gradlew
          ./gradlew publish
    env:
      GITHUB_USERNAME: ${{github.actor}}
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}